/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Source;

import java.awt.HeadlessException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Adm_Tampil extends javax.swing.JFrame {

    public Adm_Tampil() {
        initComponents();
        tampilan();
        KosongFormpass();
    }
    
    public void tampilan(){
        jpPasien.setVisible(true);
        jpPjudul.setVisible(true);
        jpPform.setVisible(true);
        jpPtable.setVisible(true);
        jpDokter.setVisible(false);
        jpDjudul.setVisible(false);
        jpDform.setVisible(false);
        jpDtable.setVisible(false);
        jpAppointment.setVisible(false);
        jpAjudul.setVisible(false);
        jpAtable.setVisible(false);
        TampilDataPasien();
    }
    
    public void TampilDataPasien(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No Pasien");
        model.addColumn("Nama Pasien");
        model.addColumn("Usia Pasien");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tanggal pengobatan");
    
        //Menampilkan data pada database ke dalam tabel
        try {
            int no=1;
            String sql="SELECT * FROM pasien";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            
            java.sql.Statement stm=conn.createStatement();
            
            java.sql.ResultSet res=stm.executeQuery(sql);
            
           while (res.next()){
           model.addRow(new Object[]{
               res.getString(1),
                res.getString(2),
                res.getString(3),
                res.getString(4),
                res.getString(5)});
            }
            tPasien.setModel(model);
        
        } catch(SQLException e){
            System.out.println("Error " + e.getMessage());
        }
    }
    
    public void TampilDataDokter(){
        DefaultTableModel model1 = new DefaultTableModel();
        model1.addColumn("ID Dokter");
        model1.addColumn("Nama Dokter");
        model1.addColumn("Jenis Kelamin");
        model1.addColumn("Jam bekerja");

    
        //Menampilkan data pada database ke dalam tabel
        try {
            int no=1;
            String sql="SELECT * FROM Dokter";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            
            java.sql.Statement stm=conn.createStatement();
            
            java.sql.ResultSet res=stm.executeQuery(sql);
            
           while (res.next()){
           model1.addRow(new Object[]{
               res.getString(1),
                res.getString(2),
                res.getString(3),
                res.getString(4)});
            }
            tDokter1.setModel(model1);        
        } catch(SQLException e){
            System.out.println("Error " + e.getMessage());
        }
    }
    
    public void TampilDataAppointment(){
        DefaultTableModel model1 = new DefaultTableModel();
        
        model1.addColumn("Nama Dokter");
        model1.addColumn("Nama Pasien");
        model1.addColumn("Keluhan");

    
        //Menampilkan data pada database ke dalam tabel
        try {
            int no=1;
            String sql="SELECT * FROM appointment";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            
            java.sql.Statement stm=conn.createStatement();
            
            java.sql.ResultSet res=stm.executeQuery(sql);
            
           while (res.next()){
           model1.addRow(new Object[]{
               res.getString(2),
                res.getString(3),
                res.getString(4)});
            }
            tAppointment.setModel(model1);        
        } catch(SQLException e){
            System.out.println("Error " + e.getMessage());
        }
    }

    public void KosongFormpass() {
        jtnopass.setEditable(true);
        jtnopass.setText(null);
        jtnapass.setText(null);
        jtuspass.setText(null);
        jcjkpass.setSelectedItem(this);
    }
    
    public void KosongFormdok() {
        jtiddok.setEditable(true);
        jtiddok.setText(null);
        jtnadok.setText(null);
        jtjbdok.setText(null);
        jcjkdok.setSelectedItem(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jpPasien = new javax.swing.JPanel();
        jpPjudul = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpPform = new javax.swing.JPanel();
        jtnopass = new javax.swing.JTextField();
        jtnapass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtuspass = new javax.swing.JTextField();
        jcjkpass = new javax.swing.JComboBox<>();
        jbPupp = new javax.swing.JButton();
        jpPtable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPasien = new javax.swing.JTable();
        jpDokter = new javax.swing.JPanel();
        jpDjudul = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jtnadok = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jcjkdok = new javax.swing.JComboBox<>();
        jtiddok = new javax.swing.JTextField();
        jbDupp = new javax.swing.JButton();
        jbDsubb = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jtjbdok = new javax.swing.JTextField();
        jpDform = new javax.swing.JPanel();
        tDokter = new javax.swing.JScrollPane();
        tDokter1 = new javax.swing.JTable();
        jpDtable = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpAppointment = new javax.swing.JPanel();
        jpAjudul = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpAtable = new javax.swing.JPanel();
        tAppoint = new javax.swing.JScrollPane();
        tAppointment = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asstets/img/Doc1-removebg-preview.png"))); // NOI18N
        jLabel1.setText("Klinik Rumbai ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Admin Dashboard");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 1040, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Menu");

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Riwayat Pengobatan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Dokter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Data Appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 290));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jpPasien.setBackground(new java.awt.Color(255, 255, 255));

        jpPjudul.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Update data Riwayat Pengobatan");

        javax.swing.GroupLayout jpPjudulLayout = new javax.swing.GroupLayout(jpPjudul);
        jpPjudul.setLayout(jpPjudulLayout);
        jpPjudulLayout.setHorizontalGroup(
            jpPjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPjudulLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel4)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jpPjudulLayout.setVerticalGroup(
            jpPjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPjudulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jpPform.setBackground(new java.awt.Color(255, 255, 255));

        jtnopass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtnopass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnopassActionPerformed(evt);
            }
        });

        jtnapass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtnapass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnapassActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Nama Pasien");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("No Pasien ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Usia Pasien");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Jenis Kelamin");

        jtuspass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtuspass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuspassActionPerformed(evt);
            }
        });

        jcjkpass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jcjkpass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih ", "Pria", "Wanita" }));

        jbPupp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbPupp.setText("Update");
        jbPupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPuppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPformLayout = new javax.swing.GroupLayout(jpPform);
        jpPform.setLayout(jpPformLayout);
        jpPformLayout.setHorizontalGroup(
            jpPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(jpPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtnopass, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jtnapass))
                .addGap(18, 18, 18)
                .addGroup(jpPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPformLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(jtuspass))
                    .addGroup(jpPformLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jcjkpass, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPformLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbPupp)
                .addGap(268, 268, 268))
        );
        jpPformLayout.setVerticalGroup(
            jpPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPformLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtnopass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jtuspass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtnapass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jcjkpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbPupp)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpPtable.setBackground(new java.awt.Color(255, 255, 255));

        tPasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tPasien);

        javax.swing.GroupLayout jpPtableLayout = new javax.swing.GroupLayout(jpPtable);
        jpPtable.setLayout(jpPtableLayout);
        jpPtableLayout.setHorizontalGroup(
            jpPtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPtableLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jpPtableLayout.setVerticalGroup(
            jpPtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPtableLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPasienLayout = new javax.swing.GroupLayout(jpPasien);
        jpPasien.setLayout(jpPasienLayout);
        jpPasienLayout.setHorizontalGroup(
            jpPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPasienLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpPform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPasienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpPjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jpPasienLayout.setVerticalGroup(
            jpPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jpPtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDokter.setBackground(new java.awt.Color(255, 255, 255));

        jpDjudul.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Nama Dokter");

        jtnadok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtnadok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnadokActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Id Dokter");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Jenis Kelamin");

        jcjkdok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jcjkdok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Pria", "Wanita" }));

        jtiddok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtiddok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtiddokActionPerformed(evt);
            }
        });

        jbDupp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbDupp.setText("Update");
        jbDupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDuppActionPerformed(evt);
            }
        });

        jbDsubb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbDsubb.setText("Submit");
        jbDsubb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDsubbActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Jam Bekerja");

        jtjbdok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtjbdok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtjbdokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDjudulLayout = new javax.swing.GroupLayout(jpDjudul);
        jpDjudul.setLayout(jpDjudulLayout);
        jpDjudulLayout.setHorizontalGroup(
            jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDjudulLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDjudulLayout.createSequentialGroup()
                        .addGroup(jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(23, 23, 23)
                        .addGroup(jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtiddok)
                            .addComponent(jtnadok, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDjudulLayout.createSequentialGroup()
                        .addComponent(jbDsubb)
                        .addGap(46, 46, 46)))
                .addGroup(jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbDupp)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcjkdok, 0, 249, Short.MAX_VALUE)
                    .addComponent(jtjbdok))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jpDjudulLayout.setVerticalGroup(
            jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDjudulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtiddok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jcjkdok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtnadok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jtjbdok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jpDjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDupp)
                    .addComponent(jbDsubb))
                .addContainerGap())
        );

        jpDform.setBackground(new java.awt.Color(255, 255, 255));

        tDokter1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tDokter1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tDokter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDokter1MouseClicked(evt);
            }
        });
        tDokter.setViewportView(tDokter1);

        javax.swing.GroupLayout jpDformLayout = new javax.swing.GroupLayout(jpDform);
        jpDform.setLayout(jpDformLayout);
        jpDformLayout.setHorizontalGroup(
            jpDformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDformLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(tDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jpDformLayout.setVerticalGroup(
            jpDformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jpDtable.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Update atau Tambah data Dokter");

        javax.swing.GroupLayout jpDtableLayout = new javax.swing.GroupLayout(jpDtable);
        jpDtable.setLayout(jpDtableLayout);
        jpDtableLayout.setHorizontalGroup(
            jpDtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDtableLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel5)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jpDtableLayout.setVerticalGroup(
            jpDtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDtableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpDokterLayout = new javax.swing.GroupLayout(jpDokter);
        jpDokter.setLayout(jpDokterLayout);
        jpDokterLayout.setHorizontalGroup(
            jpDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDokterLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jpDtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDokterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpDjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpDform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpDokterLayout.setVerticalGroup(
            jpDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDokterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jpDtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpAppointment.setBackground(new java.awt.Color(255, 255, 255));

        jpAjudul.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Lihat Data Appointment");

        javax.swing.GroupLayout jpAjudulLayout = new javax.swing.GroupLayout(jpAjudul);
        jpAjudul.setLayout(jpAjudulLayout);
        jpAjudulLayout.setHorizontalGroup(
            jpAjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAjudulLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel10)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jpAjudulLayout.setVerticalGroup(
            jpAjudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAjudulLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpAtable.setBackground(new java.awt.Color(255, 255, 255));

        tAppointment.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tAppointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tAppoint.setViewportView(tAppointment);

        javax.swing.GroupLayout jpAtableLayout = new javax.swing.GroupLayout(jpAtable);
        jpAtable.setLayout(jpAtableLayout);
        jpAtableLayout.setHorizontalGroup(
            jpAtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAtableLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(tAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jpAtableLayout.setVerticalGroup(
            jpAtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtableLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpAppointmentLayout = new javax.swing.GroupLayout(jpAppointment);
        jpAppointment.setLayout(jpAppointmentLayout);
        jpAppointmentLayout.setHorizontalGroup(
            jpAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppointmentLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jpAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAppointmentLayout.createSequentialGroup()
                        .addComponent(jpAtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAppointmentLayout.createSequentialGroup()
                        .addComponent(jpAjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        jpAppointmentLayout.setVerticalGroup(
            jpAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppointmentLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jpAjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jpAtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jpDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(jpAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jpDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 176, 810, 470));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asstets/img/bg-dash.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtiddokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtiddokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtiddokActionPerformed

    private void jtnadokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnadokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnadokActionPerformed

    private void jtuspassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuspassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuspassActionPerformed

    private void jtnapassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnapassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnapassActionPerformed

    private void jtnopassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnopassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnopassActionPerformed

    private void jbDsubbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDsubbActionPerformed
        // TODO add your handling code here:
        // Tombol SUBBMIT DOKTER
        
        try{
            String sql="INSERT INTO dokter VALUES ('" + jtiddok.getText()+"',"
                    + "'" + jtnadok.getText()+"',"
                    + "'" + jcjkdok.getSelectedItem() +"',"
                    + "'" +jtjbdok.getText()+"')";
            System.out.println(sql);
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Insert data berhasil");
            TampilDataDokter();
            KosongFormdok();
            
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jbDsubbActionPerformed

    private void jtjbdokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtjbdokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtjbdokActionPerformed

    private void tPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPasienMouseClicked
        // TODO add your handling code here:
        // Klik di TABEL PASIEN
        
        jtnopass.setEditable(false);
        
        int baris=tPasien.rowAtPoint(evt.getPoint());
        String no=tPasien.getValueAt(baris,1).toString();
        jtnopass.setText(no);
        String nama=tPasien.getValueAt(baris,2).toString();
        jtnapass.setText(nama);
        String jk=tPasien.getValueAt(baris,4).toString();
        jcjkpass.setSelectedItem(jk);
        String usia=tPasien.getValueAt(baris,3).toString();
        jtuspass.setText(usia);
    }//GEN-LAST:event_tPasienMouseClicked

    private void jbPuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPuppActionPerformed
        // TODO add your handling code here:
        // Tombol UPDATE PASIEN
        
        try{
            String sql="UPDATE pasien SET noPasien='" + jtnopass.getText()+"',"
                    + "namaPasien='" + jtnapass.getText()+"',"
                    + "usiaPasien='" +jtuspass.getText()+"',"
                    + "jenisKelamin ='" + jcjkpass.getSelectedItem() + "' WHERE noPasien='"+jtnopass.getText()+"'";
            System.out.println(sql);
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Update data berhasil");
            TampilDataPasien();
            KosongFormpass();
            
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jbPuppActionPerformed

    private void tDokter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDokter1MouseClicked
        // TODO add your handling code here:
        // Klik TABEL DOKTER
        
        jtiddok.setEditable(false);
        
        int baris=tDokter1.rowAtPoint(evt.getPoint());
        String id=tDokter1.getValueAt(baris,0).toString();
        jtiddok.setText(id);
        String nama=tDokter1.getValueAt(baris,1).toString();
        jtnadok.setText(nama);
        String jk=tDokter1.getValueAt(baris,2).toString();
        jcjkdok.setSelectedItem(jk);
        String jam=tDokter1.getValueAt(baris,3).toString();
        jtjbdok.setText(jam);
    }//GEN-LAST:event_tDokter1MouseClicked

    private void jbDuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDuppActionPerformed
        // TODO add your handling code here:
        // Tombol UPDATE DOKTER
        
        try{
            String sql="UPDATE dokter SET idDokter='" + jtiddok.getText()+"',"
                    + "namaDokter='" + jtnadok.getText()+"',"
                    + "jenisKelamin ='" + jcjkdok.getSelectedItem() +"',"
                    + "jamBekerja='" +jtjbdok.getText()
                    + "' WHERE idDokter='"+jtiddok.getText()+"'";
            System.out.println(sql);
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Update data berhasil");
            TampilDataDokter();
            KosongFormdok();
            
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jbDuppActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jpPasien.setVisible(false);
        jpPjudul.setVisible(false);
        jpPform.setVisible(false);
        jpPtable.setVisible(false);
        jpDokter.setVisible(false);
        jpDjudul.setVisible(false);
        jpDform.setVisible(false);
        jpDtable.setVisible(false);
        jpAppointment.setVisible(true);
        jpAjudul.setVisible(true);
        jpAtable.setVisible(true);
        TampilDataAppointment();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jpPasien.setVisible(false);
        jpPjudul.setVisible(false);
        jpPform.setVisible(false);
        jpPtable.setVisible(false);
        jpDokter.setVisible(true);
        jpDjudul.setVisible(true);
        jpDform.setVisible(true);
        jpDtable.setVisible(true);
        jpAppointment.setVisible(false);
        jpAjudul.setVisible(false);
        jpAtable.setVisible(false);
        TampilDataDokter();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jpPasien.setVisible(true);
        jpPjudul.setVisible(true);
        jpPform.setVisible(true);
        jpPtable.setVisible(true);
        jpDokter.setVisible(false);
        jpDjudul.setVisible(false);
        jpDform.setVisible(false);
        jpDtable.setVisible(false);
        jpAppointment.setVisible(false);
        jpAjudul.setVisible(false);
        jpAtable.setVisible(false);
        TampilDataPasien();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adm_Tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adm_Tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adm_Tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adm_Tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Adm_Tampil().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbDsubb;
    private javax.swing.JButton jbDupp;
    private javax.swing.JButton jbPupp;
    private javax.swing.JComboBox<String> jcjkdok;
    private javax.swing.JComboBox<String> jcjkpass;
    private javax.swing.JPanel jpAjudul;
    private javax.swing.JPanel jpAppointment;
    private javax.swing.JPanel jpAtable;
    private javax.swing.JPanel jpDform;
    private javax.swing.JPanel jpDjudul;
    private javax.swing.JPanel jpDokter;
    private javax.swing.JPanel jpDtable;
    private javax.swing.JPanel jpPasien;
    private javax.swing.JPanel jpPform;
    private javax.swing.JPanel jpPjudul;
    private javax.swing.JPanel jpPtable;
    private javax.swing.JTextField jtiddok;
    private javax.swing.JTextField jtjbdok;
    private javax.swing.JTextField jtnadok;
    private javax.swing.JTextField jtnapass;
    private javax.swing.JTextField jtnopass;
    private javax.swing.JTextField jtuspass;
    private javax.swing.JScrollPane tAppoint;
    private javax.swing.JTable tAppointment;
    private javax.swing.JScrollPane tDokter;
    private javax.swing.JTable tDokter1;
    private javax.swing.JTable tPasien;
    // End of variables declaration//GEN-END:variables
}
